require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/users", type: :request do

  describe "GET /show" do
    it "renders a successful response" do
      user = create(:user)
      get user_url(user[:screen_name])
      expect(response).to be_successful
      body = JSON.parse(response.body)
      expect(body["id"]).to eq user.id
      expect(body["screen_name"]).to eq user.screen_name
      expect(body["email"]).to eq user.email
    end
  end


  # describe "GET /edit" do
  #   it "renders a successful response" do
  #     user = User.create! valid_attributes
  #     get edit_user_url(user)
  #     expect(response).to be_successful
  #   end
  # end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new User" do
        user_params = attributes_for(:user)
        post users_url, params: { user: user_params }
        expect(response).to have_http_status(:created)
        expect(User.count).to eq 1
        body = JSON.parse(response.body)
        expect(body["screen_name"]).to eq user_params[:screen_name]
        expect(body["email"]).to eq user_params[:email]
      end
    end

    # context "with invalid parameters" do
    #   it "does not create a new User" do
    #     expect {
    #       post users_url, params: { user: invalid_attributes }
    #     }.to change(User, :count).by(0)
    #   end
    # end
  end
end
